=== infogrid-org/infogrid-utils/modules.fnd/org.infogrid.kernel/src/org/infogrid/modelbase/externalized/xml/model.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
//
// THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL NETMESH INC. BE LIABLE FOR ANY DIRECT,
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.
//
// The use of this software is governed by a license agreement that
// is contained in the package that you downloaded.
//
// $Date$
// -->

<!-- DTD for the InfoGrid Model XML format -->

<!ELEMENT model       ( subjectarea+ )>
<!ELEMENT subjectarea ( name, username*, userdescription*, version?, dependson?, codegen?, ( entitytype | relationshiptype)+ )>
<!ELEMENT dependson   ( ( modulerequirement | subjectareareference )+ )>
<!ELEMENT subjectareareference       ( name, minversion? )>
<!ELEMENT modulerequirement          ( name, minversion? )>
<!ELEMENT entitytype                 ( name, username*, userdescription*, icon?, supertype+, overridecode?, isabstract?, issignificant?, forwardreference?, codegen?, additionalinterface, ( propertytype | projectedpropertytype | propertytypegroup )* )>
<!ELEMENT relationshiptype           ( name, username*, userdescription*, (( src, dest ) | srcdest ), isabstract?, codegen?, propertytype* )>
<!ELEMENT propertytype               ( name, username*, userdescription*, tooverride*, datatype, defaultvalue?, isoptional?, isreadonly?, codegen?, sequencenumber? )>
<!ELEMENT projectedpropertytype      ( name, username*, userdescription*, tooverride*, datatype, defaultvalue?, isoptional?, isreadonly?, inputpropertyspecification*, projectioncode?, codegen?, sequencenumber? )>
<!ELEMENT propertytypegroup          ( name, username*, userdescription*, propertytypegroupmember+, sequencenumber? )>
<!ELEMENT propertytypegroupmember    EMPTY>
<!ELEMENT inputpropertyspecification ( traversalspecification?, propertytypereference* )>
<!ELEMENT traversalspecification     ( sequentialtraversalspecification | selectivetraversalspecification | roletypereference )>
<!ELEMENT sequentialtraversalspecification ( traversalspecification+ )>
<!ELEMENT selectivetraversalspecification  ( traversalspecification, meshobjectselector )>
<!ELEMENT meshobjectselector         ( bytypemeshobjectselector )>
<!ELEMENT bytypemeshobjectselector   EMPTY>
<!ELEMENT propertytypereference      EMPTY>
<!ELEMENT roletypereference          EMPTY>

<!ELEMENT name                (#PCDATA)>
<!ELEMENT minversion          (#PCDATA)>
<!ELEMENT version             (#PCDATA)>
<!ELEMENT username            (#PCDATA)>
<!ELEMENT userdescription     (#PCDATA)>
<!ELEMENT supertype           (#PCDATA)>
<!ELEMENT overridecode        (#PCDATA)>
<!ELEMENT projectioncode      (#PCDATA)>
<!ELEMENT isabstract          EMPTY>
<!ELEMENT isoptional          EMPTY>
<!ELEMENT isreadonly          EMPTY>
<!ELEMENT issignificant       EMPTY>
<!ELEMENT forwardreference    EMPTY>
<!ELEMENT additionalinterface (#PCDATA)>
<!ELEMENT codegen             EMPTY>
<!ELEMENT datatype            ( BlobDataType | BooleanDataType | ColorDataType | EnumeratedDataType | ExtentDataType | FloatDataType | IntegerDataType | MultiplicityDataType | PointDataType | StringDataType | TimePeriodDataType | TimeStampDataType )>
<!ELEMENT defaultvalue        (#PCDATA)>
<!ELEMENT src                 ( username*, e, refines+, MultiplicityValue, constraint+ )>
<!ELEMENT dest                ( username*, e, refines+, MultiplicityValue, constraint+ )>
<!ELEMENT srcdest             ( username*, e, refines*, top?, MultiplicityValue, constraint+ )>
<!ELEMENT e                   (#PCDATA)>
<!ELEMENT refines             (#PCDATA)>
<!ELEMENT top                 (#PCDATA)>
<!ELEMENT constraint          (#PCDATA)>
<!ELEMENT tooverride          (#PCDATA)>
<!ELEMENT sequencenumber      (#PCDATA)>
<!ELEMENT icon                EMPTY>

<!ELEMENT BlobDataType         EMPTY>
<!ELEMENT BooleanDataType      EMPTY>
<!ELEMENT ColorDataType        EMPTY>
<!ELEMENT EnumeratedDataType   ( enum+ )>
<!ELEMENT ExtentDataType       EMPTY>
<!ELEMENT FloatDataType        EMPTY>
<!ELEMENT IntegerDataType      EMPTY>
<!ELEMENT MultiplicityDataType EMPTY>
<!ELEMENT PointDataType        EMPTY>
<!ELEMENT StringDataType       EMPTY>
<!ELEMENT TimePeriodDataType   EMPTY>
<!ELEMENT TimeStampDataType    EMPTY>

<!ELEMENT MultiplicityValue (#PCDATA)>

<!ELEMENT enum ( name, username*, userdescription* )>

<!ATTLIST subjectarea
    ID ID #IMPLIED
>
<!ATTLIST entitytype
    ID ID #IMPLIED
>
<!ATTLIST securityentitytype
    ID ID #IMPLIED
>
<!ATTLIST relationshiptype
    ID ID #IMPLIED
>
<!ATTLIST propertytype
    ID ID #IMPLIED
>
<!ATTLIST projectedpropertytype
    ID ID #IMPLIED
>
<!ATTLIST propertytypegroup
    ID ID #IMPLIED
>
<!ATTLIST propertytypegroupmember
    ID ID #IMPLIED
>
<!ATTLIST supertype
    root         CDATA #IMPLIED
>
<!ATTLIST username
    locale       CDATA #IMPLIED
>
<!ATTLIST userdescription
    locale       CDATA #IMPLIED
>
<!ATTLIST icon
    path         CDATA #IMPLIED
>
<!ATTLIST defaultvalue
    code         CDATA #IMPLIED
>
<!ATTLIST codegen
    interface      CDATA #IMPLIED
    implementation CDATA #IMPLIED
>

<!ATTLIST bytypemeshobjectselector
    ID             ID    #IMPLIED
    subtypeallowed CDATA #IMPLIED
>
<!ATTLIST propertytypereference
    ID             ID    #IMPLIED
>
<!ATTLIST roletypereference
    ID             ID    #IMPLIED
>

<!ATTLIST BlobDataType
    default CDATA #IMPLIED
>
<!ATTLIST FloatDataType
    default CDATA #IMPLIED
>
<!ATTLIST IntegerDataType
    default CDATA #IMPLIED
>

=== infogrid-org/infogrid-utils/modules.fnd/org.infogrid.lid.model.yadis/infogrid-models/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file is part of InfoGrid(tm). You may not use this file except in
    compliance with the InfoGrid license. The InfoGrid license and important
    disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
    have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
    or you do not consent to all aspects of the license and the disclaimers,
    no license is granted; do not use this file.
 
    For more information about InfoGrid go to http://infogrid.org/

    Copyright 1998-2008 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
    All rights reserved.
-->

<!DOCTYPE model PUBLIC '-//InfoGrid.org//InfoGrid Model//EN' 'http://infogrid.org/dtds/model.dtd'>
<model>
    <subjectarea ID="org.infogrid.lid.model.yadis">
        <name>org.infogrid.lid.model.yadis</name>
        <username>Yadis Subject Area</username>
        <userdescription>This Subject Area covers the concepts defined by the Yadis protocol.</userdescription>

        <dependson>
            <modulereference>
                <name>org.infogrid.lid</name>
            </modulereference>
        </dependson>

        <entitytype ID="org.infogrid.lid.model.yadis#Site">
            <name>Site</name>
            <username>Site</username>
            <userdescription>Essentially a URI.</userdescription>
        </entitytype>

        <entitytype ID="org.infogrid.lid.model.yadis#Service">
            <name>Service</name>
            <username>Yadis Service</username>
            <userdescription>This represents a Yadis Service. The concept of a ServiceType is
expressed by subclasses of this EntityType.</userdescription>
            
            <propertytype ID="org.infogrid.lid.mnodel.yadis#Service/Priority">
                <name>Priority</name>
                <username>Priority</username>
                <userdescription>Priority of this Service.</userdescription>
                <datatype>
                    <IntegerDataType/>
                </datatype>
                <isoptional/>
            </propertytype>
        </entitytype>
        
        <relationshiptype ID="org.infogrid.lid.model.yadis#Site_MakesUseOf_Service">
            <name>Site_MakesUseOf_Service</name>
            <username>makes use of</username>
            <userdescription>This relates a MeshObject to the Yadis Services that it makes use of. For example,
an individual (Site) uses this relationship to identify the authentication services (Service)
that he uses for authentication, e.g. via an XRDS file they put together.</userdescription>
            <src>
              <e>org.infogrid.lid.model.yadis#Site</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.lid.model.yadis#Service</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>

        <relationshiptype ID="org.infogrid.lid.model.yadis#Service_IsProvidedAtEndpoint_Site">
            <name>Service_IsProvidedAtEndpoint_Site</name>
            <username>Is provided at</username>
            <userdescription>Expresses at which endpoints a Service is available. For example,
an identity provider (Service) uses this to list its endpoints (Site).</userdescription>
            <src>
              <e>org.infogrid.lid.model.yadis#Service</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.lid.model.yadis#Site</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>
        
        <relationshiptype ID="org.infogrid.lid.model.yadis#Site_Offers_Service">
            <name>Site_Offers_Service</name>
            <username>offers</username>
            <userdescription>Expresses which Services a Site offers. This is distinct from Service_IsProvidedAt_Site.
For example, a website (Site) may offer identity provider services (Service).</userdescription>
            <src>
              <e>org.infogrid.lid.model.yadis#Site</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.lid.model.yadis#Service</e>
              <MultiplicityValue>0:1</MultiplicityValue>
            </dest>
        </relationshiptype>
        
    </subjectarea>
</model>

=== infogrid-org/infogrid-utils/new-structure/ig-model-library/modules/org.infogrid.model.Web/infogrid-models/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file is part of InfoGrid(tm). You may not use this file except in
    compliance with the InfoGrid license. The InfoGrid license and important
    disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
    have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
    or you do not consent to all aspects of the license and the disclaimers,
    no license is granted; do not use this file.
 
    For more information about InfoGrid go to http://infogrid.org/

    Copyright 1998-2009 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
    All rights reserved.
-->

<!DOCTYPE model PUBLIC '-//InfoGrid.org//InfoGrid Model//EN' 'http://infogrid.org/dtds/model.dtd'>
<model>
    <subjectarea ID="org.infogrid.model.Web">
        <name>org.infogrid.model.Web</name>
        <username>Web Subject Area</username>
        <userdescription>This Subject Area provides concepts that may be used to represent
information found on the web.</userdescription>

        <entitytype ID="org.infogrid.model.Web/WebResource">
            <name>WebResource</name>
            <username>Web Resource</username>
            <userdescription>The resource at a URI. The URI is found in the identifier property.</userdescription>
            <maybeusedasforwardreference/>
        </entitytype>

        <relationshiptype ID="org.infogrid.model.Web/WebResource_HasLinkTo_WebResource">
            <name>WebResource_HasLinkTo_WebResource</name>
            <username>has link to</username>
            <userdescription>Captures the link relationship between Web Resources, as expressed
in HTTP Link headers, HTML link tags and the like. Specific types of link relationships are
expressed using subtypes of this RelationshipType.</userdescription>
            <src>
              <e>org.infogrid.model.Web/WebResource</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.model.Web/WebResource</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>
    </subjectarea>
</model>

=== infogrid-org/infogrid-utils/modules/org.infogrid.lid.yadis/infogrid-models/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file is part of InfoGrid(tm). You may not use this file except in
    compliance with the InfoGrid license. The InfoGrid license and important
    disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
    have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
    or you do not consent to all aspects of the license and the disclaimers,
    no license is granted; do not use this file.
 
    For more information about InfoGrid go to http://infogrid.org/

    Copyright 1998-2008 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
    All rights reserved.
-->

<!DOCTYPE model PUBLIC '-//InfoGrid.org//InfoGrid Model//EN' 'http://infogrid.org/dtds/model.dtd'>
<model>
    <subjectarea ID="org.infogrid.lid.yadis">
        <name>org.infogrid.lid.yadis</name>
        <username>Yadis Subject Area</username>
        <userdescription>This Subject Area covers the concepts defined by the Yadis protocol.</userdescription>

        <entitytype ID="org.infogrid.lid.yadis#Site">
            <name>Site</name>
            <username>Site</username>
            <userdescription>Essentially a URI.</userdescription>
<!--
            <propertytype ID="org.infogrid.lid.yadis#Site/URI">
                <name>URI</name>
                <username>URI</username>
                <userdescription>The URI of this site.</userdescription>
                <datatype>
                    <StringDataType/>
                </datatype>
                <isoptional/>
            </propertytype>
-->
        </entitytype>

        <entitytype ID="org.infogrid.lid.yadis#Service">
            <name>Service</name>
            <username>Yadis Service</username>
            <userdescription>This represents a Yadis Service. The concept of a ServiceType is
              expressed by subclasses of this EntityType.</userdescription>
            
            <propertytype ID="org.infogrid.lid.yadis#Service/Priority">
                <name>Priority</name>
                <username>Priority</username>
                <userdescription>Priority of this Service.</userdescription>
                <datatype>
                    <IntegerDataType/>
                </datatype>
                <isoptional/>
            </propertytype>
        </entitytype>
        
        <relationshiptype ID="org.infogrid.lid.yadis#Site_MakesUseOf_Service">
            <name>Site_MakesUseOf_Service</name>
            <username>makes use of</username>
            <userdescription>This relates a MeshObject to the Yadis Services that it makes use of.</userdescription>
            <src>
              <e>org.infogrid.lid.yadis#Site</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.lid.yadis#Service</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>

        <relationshiptype ID="org.infogrid.lid.yadis#Service_IsProvidedAtEndpoint_Site">
            <name>Service_IsProvidedAtEndpoint_Site</name>
            <username>Is provided at</username>
            <userdescription>Expresses at which endpoints a Service is available.</userdescription>
            <src>
              <e>org.infogrid.lid.yadis#Service</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.lid.yadis#Site</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>
        
        <relationshiptype ID="org.infogrid.lid.yadis#Site_Offers_Service">
            <name>Site_Offers_Service</name>
            <username>offers</username>
            <userdescription>Expresses which Services a Site offers. This is distinct from Service_IsProvidedAt_Site.</userdescription>
            <src>
              <e>org.infogrid.lid.yadis#Site</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.lid.yadis#Service</e>
              <MultiplicityValue>0:1</MultiplicityValue>
            </dest>
        </relationshiptype>
        
    </subjectarea>
</model>

=== infogrid-org/infogrid-utils/modules.fnd/org.infogrid.model.Account/infogrid-models/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file is part of InfoGrid(tm). You may not use this file except in
    compliance with the InfoGrid license. The InfoGrid license and important
    disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
    have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
    or you do not consent to all aspects of the license and the disclaimers,
    no license is granted; do not use this file.
 
    For more information about InfoGrid go to http://infogrid.org/

    Copyright 1998-2009 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
    All rights reserved.
-->

<!DOCTYPE model PUBLIC '-//InfoGrid.org//InfoGrid Model//EN' 'http://infogrid.org/dtds/model.dtd'>
<model>
    <subjectarea ID="org.infogrid.model.Account">
        <name>org.infogrid.model.Account</name>
        <username>Accounts Security Subject Area</username>
        <userdescription>This Subject Area defines the concept of an account on a system
        as well as different categories of accounts.</userdescription>

        <entitytype ID="org.infogrid.model.Account/AccountCategory">
            <name>AccountCategory</name>
            <username>Account Category</username>
            <userdescription>Categorizes accounts on a system.</userdescription>
        </entitytype>

        <relationshiptype ID="org.infogrid.model.Account/AccountCategory_CategorizesAccount_MeshObject">
            <name>AccountCategory_Categorizes_MeshObject</name>
            <username>Categorizes</username>
            <userdescription>Collects MeshObjects that act as Accounts into AccountCategories.</userdescription>
            <src>
              <e>org.infogrid.model.Account/AccountCategory</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>

        <relationshiptype ID="org.infogrid.model.Account/AccountCategory_Implies_AccountCategory">
            <name>AccountCategory_Implies_AccountCategory</name>
            <username>Implies</username>
            <userdescription>Enables the creation of inheritance hierarchies for AccountCategories.
            Expresses that members of one AccountCategory are also considered members of the
            implied AccountCategories.</userdescription>
            <src>
              <e>org.infogrid.model.Account/AccountCategory</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.model.Account/AccountCategory</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>

    </subjectarea>
</model>

=== infogrid-org/infogrid-utils/modules.fnd/org.infogrid.model.Bookmark/infogrid-models/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file is part of InfoGrid(tm). You may not use this file except in
    compliance with the InfoGrid license. The InfoGrid license and important
    disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
    have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
    or you do not consent to all aspects of the license and the disclaimers,
    no license is granted; do not use this file.

    For more information about InfoGrid go to http://infogrid.org/

    Copyright 1998-2009 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
    All rights reserved.
-->

<!DOCTYPE model PUBLIC '-//InfoGrid.org//InfoGrid Model//EN' 'http://infogrid.org/dtds/model.dtd'>
<model>
    <subjectarea ID="org.infogrid.model.Bookmark#_SubjectArea">
        <name>org.infogrid.model.Bookmark</name>
        <username>Bookmarking Subject Area</username>
        <userdescription>Bookmarking Subject Area</userdescription>

        <entitytype ID="org.infogrid.model.Bookmark#BookmarkCollection">
            <name>BookmarkCollection</name>
            <username>Bookmark Library</username>
            <userdescription>A collection of book marks.</userdescription>
            <propertytype ID="org.infogrid.model.Bookmark#BookmarkCollection/Name">
                <name>Name</name>
                <username>Name</username>
                <userdescription>The name of the Bookmark Collection</userdescription>
                <datatype>
                    <StringDataType/>
                </datatype>
                <isoptional/>
            </propertytype>
        </entitytype>

        <entitytype ID="org.infogrid.model.Bookmark#Bookmark">
            <name>Bookmark</name>
            <username>Bookmark</username>
            <userdescription>A bookmark</userdescription>
            <propertytype ID="org.infogrid.model.Bookmark#Bookmark/Name">
                <name>Name</name>
                <username>Name</username>
                <userdescription>The name of the bookmark</userdescription>
                <datatype>
                    <StringDataType/>
                </datatype>
                <isoptional/>
            </propertytype>
        </entitytype>

        <relationshiptype ID="org.infogrid.model.Bookmark#BookmarkCollection_Collects_Bookmark">
            <name>BookmarkCollection_Collects_Bookmark</name>
            <username>Collects</username>
            <userdescription>Relates a Bookmark to the BookmarkCollection in which it is collected.</userdescription>
            <src>
              <e>org.infogrid.model.Bookmark#BookmarkCollection</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.model.Bookmark#Bookmark</e>
              <MultiplicityValue>1:1</MultiplicityValue>
            </dest>
        </relationshiptype>

        <relationshiptype ID="org.infogrid.model.Bookmark#Bookmark_Bookmarks_MeshObject">
            <name>Bookmark_Bookmarks_MeshObject</name>
            <username>bookmarks</username>
            <userdescription>Relates the Bookmark to the MeshObject that is being bookmarked.</userdescription>
            <src>
              <e>org.infogrid.model.Bookmark#Bookmark</e>
              <MultiplicityValue>1:1</MultiplicityValue>
            </src>
            <dest>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>
        
        <relationshiptype ID="org.infogrid.model.Tagging#MeshObject_Uses_BookmarkCollection">
            <name>MeshObject_Uses_BookmarkCollection</name>
            <username>Uses</username>
            <userdescription>Enables a MeshObject (such as a person) to identify those BookmarkCollections they use.</userdescription>
            <src>
              <MultiplicityValue>0:N</MultiplicityValue>
            </src>
            <dest>
              <e>org.infogrid.model.Bookmark#BookmarkCollection</e>
              <MultiplicityValue>0:N</MultiplicityValue>
            </dest>
        </relationshiptype>

    </subjectarea>
</model>
